<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>preview</LangVersion>
        <RuntimeIdentifiers>win-x64; linux-x64</RuntimeIdentifiers>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ManagedBass" Version="4.0.2"/>
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Assets/stepped-on.ogg">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup Condition="'$(RuntimeIdentifier)' == 'win-x64' OR '$(RuntimeIdentifier)' == 'win-x86' OR '$(RuntimeIdentifier)' == 'win-arm64'">
        <Content Include="../OpenFreqAudio/Assets/windows/**/*">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
            <TargetPath>%(Filename)%(Extension)</TargetPath>
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        </Content>
    </ItemGroup>

    <ItemGroup Condition="'$(RuntimeIdentifier)' == 'linux-x64' OR '$(RuntimeIdentifier)' == 'linux-arm64'">
        <Content Include="../OpenFreqAudio/Assets/linux/**/*">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
            <TargetPath>%(Filename)%(Extension)</TargetPath>
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\openfreq\OpenFreq.Common\OpenFreq.Common.csproj" />
    </ItemGroup>

</Project>
