<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>preview</LangVersion>
        <RuntimeIdentifiers>win-x64; linux-x64</RuntimeIdentifiers>
    </PropertyGroup>

    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
        <DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="OpenFreqAudio.Tests" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="ManagedBass" Version="4.0.2" />
        <PackageReference Include="ManagedBass.Mix" Version="4.0.2" />
        <PackageReference Include="ManagedBass.Enc" Version="4.0.2" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0" />
        <PackageReference Include="NWaves" Version="0.9.6" />
    </ItemGroup>

    <ItemGroup Condition="'$(RuntimeIdentifier)' == 'win-x64' OR '$(RuntimeIdentifier)' == 'win-x86' OR '$(RuntimeIdentifier)' == 'win-arm64'">
        <Content Include="../OpenFreqAudio/Assets/windows/**/*">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
            <TargetPath>%(Filename)%(Extension)</TargetPath>
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        </Content>
    </ItemGroup>

    <ItemGroup Condition="'$(RuntimeIdentifier)' == 'linux-x64' OR '$(RuntimeIdentifier)' == 'linux-arm64'">
        <Content Include="../OpenFreqAudio/Assets/linux/**/*">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
            <TargetPath>%(Filename)%(Extension)</TargetPath>
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        </Content>
    </ItemGroup>
</Project>
